version: '3'
services:

  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: always


  rabbit:
    image: rabbitmq:3.12.4-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4001:80"
    environment:
      - GUNICORN_BIND=0.0.0.0:80
    restart: "no"

  history:
    image: history
    build: 
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    ports:
      - "4002:80"
    environment:
      - GUNICORN_BIND=0.0.0.0:80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"